In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.14.0


In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 0s 0us/step


In [4]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [5]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.01790956,  0.42964187, -0.3881048 , -0.05803433, -0.22448519,
         0.50879514,  0.05542318,  0.8423859 , -0.18430473,  0.11576883]],
      dtype=float32)

In [6]:
tf.nn.softmax(predictions).numpy()

array([[0.08503584, 0.12835567, 0.05665943, 0.07881702, 0.06673156,
        0.13892835, 0.08828643, 0.19394006, 0.06946746, 0.09377817]],
      dtype=float32)

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [8]:
loss_fn(y_train[:1], predictions).numpy()

1.9737968

In [9]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [10]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 14s 7ms/step - loss: 0.2970 - accuracy: 0.9127
Epoch 2/5
1875/1875 [==============================] - 10s 6ms/step - loss: 0.1442 - accuracy: 0.9567
Epoch 3/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.1060 - accuracy: 0.9678
Epoch 4/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0867 - accuracy: 0.9728
Epoch 5/5
1875/1875 [==============================] - 10s 6ms/step - loss: 0.0735 - accuracy: 0.9769


In [11]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0749 - accuracy: 0.9768 - 751ms/epoch - 2ms/step


[0.07491549104452133, 0.9768000245094299]

In [12]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [13]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.36249739e-07, 1.03695106e-08, 6.22301523e-05, 4.60082898e-04,
        7.45124462e-10, 1.02911940e-07, 1.36911728e-12, 9.99471366e-01,
        2.27354732e-07, 6.01227157e-06],
       [1.36624925e-08, 1.07059268e-05, 9.99744952e-01, 2.50485045e-05,
        2.60705544e-16, 2.19255802e-04, 1.83462205e-08, 6.12329024e-12,
        7.79673481e-09, 7.35934650e-17],
       [1.36133309e-07, 9.99166012e-01, 2.39932386e-04, 6.89241006e-06,
        4.65118574e-05, 1.92990938e-05, 1.46661987e-04, 2.49354140e-04,
        1.22036276e-04, 3.23038603e-06],
       [9.99498606e-01, 4.86167773e-10, 1.87687139e-04, 1.10532348e-07,
        3.97525082e-06, 1.10136455e-06, 3.95275565e-05, 1.06217976e-05,
        3.00291390e-07, 2.58104294e-04],
       [2.07233302e-06, 3.01297542e-10, 1.68088281e-05, 2.77320389e-08,
        9.81799185e-01, 3.61658476e-06, 1.20491686e-05, 8.28073898e-05,
        3.75687669e-05, 1.80457886e-02]], dtype=float32)>